# Leader
- type: job
  id: ERTLeader
  name: job-name-ertleader
  description: job-description-ertleader
  playTimeTracker: JobERTLeader
  setPreference: false
  startingGear: ERTLeaderGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, DeathRattleImplantCentcomm ]

- type: startingGear
  id: ERTLeaderGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTLeader
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTLeaderFilled
    neck: Whistle
    pocket1: WeaponPistolN1984
    pocket2: FlashlightLantern
  suit_storage:
    - WeaponDisablerSMG
  storage:
    back:
    - PortableRecharger
    - Zipties
    - Zipties
    - PinpointerNuclear
    - PhoneInstrument
    - CrowbarRed
    - HoloprojectorField
    - TelescopicShield

- type: startingGear
  id: ERTLeaderGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTLeaderFilled
    neck: Whistle
    pocket1: WeaponPistolN1984
    pocket2: TelescopicShield
  storage:
    back:
    - PortableRecharger
    - WeaponDisablerSMG
    - Zipties
    - Zipties
    - PinpointerNuclear
    - PhoneInstrument
    - CrowbarRed
    - HoloprojectorField

- type: startingGear
  id: ERTLeaderGearArmed
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTLeader
    back: ClothingBackpackERTLeader
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedSec
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTLeader
    id: ERTLeaderPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTLeaderFilled
    neck: Whistle
    pocket1: WeaponPistolN1984
    pocket2: WeaponDisabler
  storage:
    back:
    - PortableRecharger
    - WeaponSubMachineGunDrozd
    - Zipties
    - Zipties
    - PinpointerNuclear
    - PhoneInstrument
    - CrowbarRed
    - HoloprojectorField
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGunIncendiary

# Chaplain
- type: job
  id: ERTChaplain
  name: job-name-ertchaplain
  description: job-description-ertchaplain
  playTimeTracker: JobERTChaplain
  setPreference: false
  startingGear: ERTChaplainGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles

- type: startingGear
  id: ERTChaplainGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsCombatFilled
    head: ClothingHeadHatFez
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: WeaponPistolMk58
    pocket2: FlashlightLantern
  storage:
    back:
    - BoxBodyBag
    - BoxCandle
    - MagazinePistol
    - CrowbarRed
    - Bible
    - Lighter
    - DrinkWaterMelonJuiceJug
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    belt:
    - Lantern
    - Lantern
    - Lantern
    - Lantern

- type: startingGear
  id: ERTChaplainGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTChaplain
    back: ClothingBackpackERTChaplain
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    neck: ClothingNeckStoleChaplain
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTChaplain
    id: ERTChaplainPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltStorageWaistbag
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - BoxBodyBag
    - BoxCandle
    - MagazinePistol
    - CrowbarRed
    - Bible
    - Lighter
    - DrinkWaterMelonJuiceJug
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - FoodBakedBunHotX
    - CombatKnife
    belt:
    - Lantern
    - Lantern
    - Lantern
    - Lantern

# Engineer
- type: job
  id: ERTEngineer
  name: job-name-ertengineer
  description: job-description-ertengineer
  playTimeTracker: JobERTEngineer
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTEngineerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTEngineer
    eyes: ClothingEyesHudDiagnostic
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTEngineerFilled
    pocket1: WeaponPistolMk58
    pocket2: FlashlightLantern
  inhand:
  - ClothingBackpackDuffelEngineeringFilled
  storage:
    back:
    - RCD
    - RCDAmmo
    - RCDAmmo
    - CombatKnife
    - trayScanner
    - GasAnalyzer
    - AccessConfigurator
    - SheetSteel
    - SheetRUGlass
    - SheetPlasteel
    - MiningDrill
    - CableApcStack
    - MetalFoamGrenade
    - MetalFoamGrenade
    - MetalFoamGrenade

- type: startingGear
  id: ERTEngineerGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudDiagnostic
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTEngineerFilled
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  inhand:
  - ClothingBackpackDuffelEngineeringFilled
  storage:
    back:
    - RCD
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - trayScanner
    - GasAnalyzer
    - AccessConfigurator
    - SheetSteel
    - SheetRUGlass
    - SheetPlasteel
    - MiningDrill
    - CableApcStack
    - MetalFoamGrenade
    - MetalFoamGrenade
    - MetalFoamGrenade

- type: startingGear
  id: ERTEngineerGearArmed
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTEngineer
    back: ClothingBackpackERTEngineer
    shoes: ClothingShoesBootsMag
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudDiagnostic
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTEngineer
    id: ERTEngineerPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTEngineerFilled
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  inhand:
    - ClothingBackpackDuffelEngineeringFilled
  storage:
    back:
    - RCD
    - RCDAmmo
    - RCDAmmo
    - RCDAmmo
    - trayScanner
    - GasAnalyzer
    - AccessConfigurator
    - WeaponSubMachineGunDrozd
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGunIncendiary
    - MagazinePistolSubMachineGunUranium
    - MiningDrill
    - CableApcStack
    - MetalFoamGrenade
    - MetalFoamGrenade

# Security
- type: job
  id: ERTSecurity
  name: job-name-ertsecurity
  description: job-description-ertsecurity
  playTimeTracker: JobERTSecurity
  setPreference: false
  startingGear: ERTEngineerGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTSecurity
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    neck: SecurityWhistle
    belt: ClothingBeltMilitaryWebbingERTSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: FlashlightLantern
  storage:
    back:
    - WeaponDisablerSMG
    - Stunbaton
    - TearGasGrenade
    - GrenadeStinger
    - BoxZiptie
    - GrenadeFlashBang
    - CrowbarRed
    - HoloprojectorSecurity

- type: startingGear
  id: ERTSecurityGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    neck: SecurityWhistle
    belt: ClothingBeltMilitaryWebbingERTSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: TelescopicShield
  storage:
    back:
    - WeaponDisablerSMG
    - Stunbaton
    - TearGasGrenade
    - GrenadeStinger
    - BoxZiptie
    - GrenadeFlashBang
    - CrowbarRed
    - HoloprojectorSecurity

- type: startingGear
  id: ERTSecurityGearRifleman
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: TelescopicShield
  inhand:
    - WeaponRifleLecter
  storage:
    back:
    - WeaponPulseCarbine
    - GrenadeShrapnel
    - SmokeGrenade
    - CrowbarRed
    - MagazineRifle
    - MagazineRifle
    - MagazineRifleIncendiary
    - MagazineRifleUranium

- type: startingGear
  id: ERTSecurityGearBreacher
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTSecurityFilled
    pocket1: WeaponPistolMk58
    pocket2: EnergyShield
  storage:
    back:
    - WeaponShotgunEnforcer
    - JawsOfLife
    - SmokeGrenade
    - BoxLethalshot
    - BoxShotgunIncendiary
    - BoxShotgunSlug
    - EnergySword
    - SmokeGrenade
    - C4
    - C4
    - C4
    - C4

- type: startingGear
  id: ERTSecurityGearGrenadier
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTSecurity
    back: ClothingBackpackERTSecurity
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTSecurity
    id: ERTSecurityPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTSecurityFilled
    pocket1: WeaponPistolMk58
  storage:
    back:
    - WeaponSubMachineGunDrozd
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGunIncendiary
    - MagazinePistolSubMachineGunUranium
    - CrowbarRed
    - SmokeGrenade
    - SmokeGrenade
    - EmpGrenade
    - EmpGrenade
    - GrenadeShrapnel
    - GrenadeShrapnel
    - GrenadeShrapnel
    - ExGrenade
    - ExGrenade
    - ExGrenade
    - ExGrenade

# Medical
- type: job
  id: ERTMedical
  name: job-name-ertmedic
  description: job-description-ertmedic
  playTimeTracker: JobERTMedical
  setPreference: false
  startingGear: ERTMedicalGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTMedicalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTMedic
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterVestWeb
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTMedicFilled
    pocket1: WeaponPistolMk58
    pocket2: FlashlightLantern
  inhand:
    - ClothingBackpackDuffelMedical
  storage:
    back:
    - JugPunctTranex
    - JugPyraDerma
    - JugTrico
    - BeakerSmallDex+
    - BeakerSmallSaline
    - BeakerSmallBruiz
    - BeakerSmallLace
    - BeakerSmallArith
    - BeakerSmallDiphen
    - Hypospray

- type: startingGear
  id: ERTMedicalGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTMedicFilled
    pocket1: WeaponPistolMk58
    pocket2: Hypospray
  inhand:
    - ClothingBackpackDuffelMedical
  storage:
    back:
    - JugPunctTranex
    - JugPyraDerma
    - JugTrico
    - BeakerSmallDex+
    - BeakerSmallSaline
    - BeakerSmallBruiz
    - BeakerSmallLace
    - BeakerSmallArith
    - BeakerSmallDiphen

- type: startingGear
  id: ERTMedicalGearArmed
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTMedic
    back: ClothingBackpackERTMedical
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesHudMedical
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitERTMedical
    id: ERTMedicPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTMedicFilled
    pocket1: WeaponPistolMk58
    pocket2: Hypospray
  inhand:
    - WeaponSubMachineGunDrozd
    - ClothingBackpackDuffelMedical
  storage:
    back:
    - JugPunctTranex
    - JugPyraDerma
    - JugTrico
    - BeakerSmallDex+
    - BeakerSmallSaline
    - BeakerSmallBruiz
    - BeakerSmallLace
    - BeakerSmallArith
    - BeakerSmallDiphen
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGunIncendiary
    - MagazinePistolSubMachineGunUranium

# Janitor
- type: job
  id: ERTJanitor
  name: job-name-ertjanitor
  description: job-description-ertjanitor
  playTimeTracker: JobERTJanitor
  setPreference: false
  startingGear: ERTJanitorGearEVA
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand

- type: startingGear
  id: ERTJanitorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesGaloshes
    mask: ClothingMaskGasERT
    head: ClothingHeadHelmetERTJanitor
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterVestWeb
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTJanitorFilled
    pocket1: WeaponPistolMk58
    pocket2: FlashlightLantern
  storage:
    back:
    - AdvMopItem
    - Screwdriver
    - WelderIndustrialAdvanced
    - TrashBag
    - TrashBag
    - CombatKnife
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade

- type: startingGear
  id: ERTJanitorGearEVA
  equipment:
    jumpsuit: ClothingUniformJumpsuitERTJanitor
    back: ClothingBackpackERTJanitor
    shoes: ClothingShoesBootsMagSci
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesChemical
    gloves: ClothingHandsGlovesColorPurple
    outerClothing: ClothingOuterHardsuitERTJanitor
    id: ERTJanitorPDA
    ears: ClothingHeadsetAltCentCom
    belt: ClothingBeltMilitaryWebbingERTJanitorFilled
    pocket1: WeaponPistolMk58
    pocket2: CombatKnife
  storage:
    back:
    - AdvMopItem
    - Screwdriver
    - WelderIndustrialAdvanced
    - TrashBag
    - TrashBag
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
    - CleanerGrenade
